<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SPSApi.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
    <Folder Include="Features\" />
    <Folder Include="Features\CreateAssetModel\" />
    <Folder Include="Features\CreateBrand\" />
    <Folder Include="Features\CreateProduct\" />
    <Folder Include="Features\DeleteAssetModel\" />
    <Folder Include="Features\DeleteBrand\" />
    <Folder Include="Features\DeleteProduct\" />
    <Folder Include="Features\ListPartNumbers\" />
    <Folder Include="Features\ListProducts\" />
    <Folder Include="Features\SetProductActive\" />
    <Folder Include="Features\UpdateProduct\" />
  </ItemGroup>

  <PropertyGroup>
    <!-- TargetFramework, Nullable, ImplicitUsings, LangVersion -> Directory.Build.props -->
  </PropertyGroup>

</Project>
