<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SPSApi.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
    <Folder Include="Features\" />
    <Folder Include="Features\CreateProduct\" />
  </ItemGroup>

  <PropertyGroup>
    <!-- TargetFramework, Nullable, ImplicitUsings, LangVersion -> Directory.Build.props -->
  </PropertyGroup>

</Project>
