<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- TargetFramework, Nullable, ImplicitUsings, LangVersion -> Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Identity\SPSApi.Modules.Identity.csproj" />
    <ProjectReference Include="..\Modules\Customers\SPSApi.Modules.Customers.csproj" />
    <ProjectReference Include="..\Modules\Catalog\SPSApi.Modules.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Assets\SPSApi.Modules.Assets.csproj" />
    <ProjectReference Include="..\Modules\Inventory\SPSApi.Modules.Inventory.csproj" />
    <ProjectReference Include="..\Modules\Contracts\SPSApi.Modules.Contracts.csproj" />
    <ProjectReference Include="..\Modules\Profitability\SPSApi.Modules.Profitability.csproj" />
  </ItemGroup>

</Project>
